quizsite/quizsite/urls.py
from django.contrib import admin
from django.urls import path
from backend import views
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

from django.conf.urls.static import static

urlpatterns = [
        re_path(
        r'^statics/(?P<path>.*)$',
        serve,
        {
            'document_root': settings.STATIC_URL,
            'show_indexes': True,  # must be True to render file list
        },
    ),
    path('',views.home,name='home_page'),
    path('admin/', admin.site.urls),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('user/', views.userpage, name='userpage'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/<str:course_name>/', views.course_item, name='course_item'),
    path('courses/<str:course_name>/delete/', views.course_delete, name='course_delete'),
    path('courses/<str:course_name>/browse/', views.course_browse_redir, name='course_browse_redir'),
    path('courses/<str:course_name>/browse/<int:page_number>/', views.course_browse, name='course_browse'),
    path('courses/<str:course_name>/browse/end/', views.course_browse_end, name='course_browse_end'),
    path('courses/<str:course_name>/edit/', views.course_edit_redir, name='course_edit_redir'),
    path('courses/<str:course_name>/edit/pages/', views.course_page_manager, name='course_page_manager'),
    path('courses/<str:course_name>/edit/pages/delete/<int:page_number>/', views.course_page_manager_delete, name='course_page_manager_delete'),
    path('courses/<str:course_name>/edit/<int:page_number>/', views.course_edit, name='course_edit'),
    path('groups/',views.group_browse,name='group_browse'),
    path('groups/create/',views.group_create,name='group_create'),
    path('groups/<str:group_name>/',views.group_redir,name='group_redir'),
    path('groups/<str:group_name>/edit/',views.group_edit,name='group_edit'),
    path('groups/<str:group_name>/delete/',views.group_delete,name='group_delete'),
    path('groups/<str:group_name>/students/',views.group_students,name='group_students'),
    path('groups/<str:group_name>/students/delete/',views.group_students_delete_redir,name='group_students_delete_redir'),
    path('groups/<str:group_name>/students/delete/<str:student_name>/',views.group_students_delete,name='group_students_delete'),
    path('groups/<str:group_name>/students/delete/',views.group_assignments_delete_redir,name='group_assignments_delete_redir'),
    path('groups/<str:group_name>/assignments/',views.group_assignments,name='group_assignments'),
    path('groups/<str:group_name>/assignments/delete/<str:course_name>/',views.group_assignments_delete,name='group_assignments_delete'),
    path('groups/<str:group_name>/assignments/<str:course_name>/',views.group_assignments_item,name='group_assignments_item'),
    path('groups/<str:group_name>/assignments/<str:course_name>/<str:student_name>/',views.group_assignments_user_results,name='group_assignments_user_results'),
    path('groups/<str:group_name>/notifications/',views.group_notifications,name='group_notifications'),
    path('assignments/',views.assignments_browse,name='assignments_browse'),
    path('user/settings/',views.user_settings,name='user_settings'),
    path('notifications/',views.notifications,name='notifications'),
    path('logout/', views.logout_user, name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizsite/backend/models.py
from django.db import models

from django.contrib.auth.models import User

from django.core.files.storage import FileSystemStorage

from django.conf import settings



# Create your models here.
class Course(models.Model):
    name=models.CharField(max_length=30)
    author=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    ACCESS_LEVEL = (
        ('A','Public'),
        ('B','Unlisted'),
        ('C','Private'),
    )
    description=models.TextField(default='')
    access=models.CharField(max_length=1,choices=ACCESS_LEVEL,default='C')
    is_quiz=models.BooleanField(default=False)
    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.name=self.name.replace('/','').replace('?','')
        super(Course,self).save(*args,**kwargs)

class CoursePage(models.Model):
    parent=models.ForeignKey(Course,on_delete=models.CASCADE)
    number=models.IntegerField()
    title=models.TextField(default='')
    text=models.TextField(default='')
    is_quiz=models.BooleanField(default=False)
    #has_answer=models.BooleanField(default=False)

    ANSWER_TYPE = (
        ('N',None),
        ('T','Text'),
        ('S','Singular Choice'),
        ('M','Multiple Choice'),
        ('F','File Upload'),
    )
    answer_type=models.CharField(max_length=1,choices=ANSWER_TYPE,default='N')

    time=models.IntegerField(default=15,null=True)

    def __str__(self):
        return 'Page '+str(self.number)+' of '+self.parent.name

#Answer form models
#Concept: several models each storing an answer for pages that have something to submit. Each submission is done by a specific user so that it can be pulled up later on.

class CoursePageAnswer(models.Model): #abstract parent
    page=models.OneToOneField(CoursePage,on_delete=models.CASCADE)
    #user=models.OneToOneField(User,on_delete=models.SET_NULL,null=True)
    class Meta:
        abstract=True
    def __str__(self):
        return 'Answer type for page '+str(self.page.title)

#testing out a different approach
class PageAnswerText(CoursePageAnswer):
    text=models.TextField(default='',blank=True)
    is_choice=models.BooleanField(default=False)
    is_multiple=models.BooleanField(default=False)
    is_file=models.BooleanField(default=False)
    choices=models.JSONField(default=dict,blank=True)
    correct_choices=models.JSONField(default=dict,blank=True)
    # grading
    correct_grade=models.IntegerField(default=0)
    incorrect_penalty=models.IntegerField(default=0)

#this simply didn't work :(
'''
    def __init(self,*args,CHOICE_DATA=None,**kwargs):
        #CHOICE_DATA=kwargs.pop('CHOICE_DATA',None)
        super(PageAnswerText,self).__init__(*args,**kwargs)
        if CHOICE_DATA != None:
            self._apply_choices(CHOICE_DATA)
        
    def _apply_choices(self,CHOICE_DATA):
        if CHOICE_DATA:
            self.text=models.TextField(default='',choices=CHOICE_DATA)
        else:
            self.text=models.TextField(default='')

'''

class StudentAnswer(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    page=models.ForeignKey(CoursePage,on_delete=models.CASCADE)
    ANSWER_TYPE = (
        ('N',None),
        ('T','Text'),
        ('S','Singular Choice'),
        ('M','Multiple Choice'),
        ('F','File Upload'),
    )
    answer_type=models.CharField(max_length=1,choices=ANSWER_TYPE,default='N') #for nuking non-matching responses
    class Meta:
        abstract=True
class StudentAnswerText(StudentAnswer):
    response=models.TextField(default='',blank=True)
    def __str__(self):
        return 'Answer of '+str(self.user)+' for '+str(self.page)
class StudentAnswerFile(StudentAnswer):
    response=models.FileField(default=None,upload_to='user_responses/',null=True,blank=True)
    def __str__(self):
        return 'File Answer of '+str(self.user)+' for '+str(self.page)

class UserPerms(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    is_teacher=models.BooleanField(default=False) #can create courses, groups
    is_manager=models.BooleanField(default=False)
    def __str__(self):
        return self.user.username+'\'s permissions'
    
class UserGroups(models.Model):
    name=models.CharField(max_length=100)
    teacher=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    def save(self,*args,**kwargs):
        self.name=self.name.replace('/','').replace('?','')
        super(UserGroups,self).save(*args,**kwargs)
    def __str__(self):
        return self.name

class GroupEnrollment(models.Model):
    student=models.ForeignKey(User,on_delete=models.CASCADE)
    group=models.ForeignKey(UserGroups,on_delete=models.CASCADE)

    def __str__(self):
        return self.student.username+' in '+self.group.name

class GroupAssignments(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    group=models.ForeignKey(UserGroups,on_delete=models.CASCADE)
    deadline=models.DateTimeField(null=True,default=None,blank=True)

    def __str__(self):
        return self.course.name+' in '+self.group.name

class CurrentPageControl(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    page=models.ForeignKey(CoursePage,on_delete=models.CASCADE)
    student=models.ForeignKey(User,on_delete=models.CASCADE)

class Notifications(models.Model):
    group=models.ForeignKey(UserGroups,on_delete=models.CASCADE)
    title=models.TextField(default='')
    text=models.TextField(default='')
    read=models.ManyToManyField(User,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    
class UserPFP(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    pfp=models.ImageField(null=True,blank=True,upload_to='user_pfps/')

quizsite/backend/forms.py
from django import forms

from django.contrib.admin.widgets import AdminDateWidget

class RegisterForm(forms.Form): #reused from the last year's project
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'placeholder': 'Email','class': 'login-input-box'}))
    login = forms.CharField(label='Login', widget=forms.TextInput(attrs={'placeholder': 'Login','class': 'login-input-box'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'login-input-box'}))
    password_verify = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password','class': 'login-input-box'})) #, 'class': 'square_login' - cut out as no css work is done at this point

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""

class AuthForm(forms.Form):
    # login = forms.CharField(label='Login', max_length=100)
    login = forms.CharField(label='Login', widget=forms.TextInput(attrs={'placeholder': 'Login', 'class': 'login-input-box'}))

    # password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'login-input-box'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""

class SearchForm(forms.Form):
    search = forms.CharField(label='Search',required=False, widget=forms.TextInput(attrs={'placeholder': 'Type the course name here', 'class': 'search-box'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""

class CourseForm(forms.Form):
    ACCESS_LEVEL = (
        ('A','Public'),
        ('B','Unlisted'),
        ('C','Private'),
    )
    name=forms.CharField(label='Name',widget=forms.TextInput(attrs={'placeholder':'Course Name','class':'form-field'}))
    description=forms.CharField(label='Description',required=False,widget=forms.Textarea(attrs={'placeholder':'Description','class':'form-field description'}))
    access=forms.ChoiceField(choices=ACCESS_LEVEL,widget=forms.Select(attrs={'class':'form-field'}))
    quiz=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'checkbox-editor'}))
    #image=forms.ImageField(required=False)
class CoursePageForm(forms.Form):
    A_TYPE = (
        ('N',None),
        ('T','Text'),
        ('S','Singular Choice'),
        ('M','Multiple Choice'),
        ('F','File Upload'),
    )
    answer_type=forms.ChoiceField(choices=A_TYPE,widget=forms.Select(attrs={'class':'form-field','id':'answer_type','onChange':'displayWarning();'}))
    title=forms.CharField(label='Page Title',widget=forms.TextInput(attrs={'placeholder':'Page Name','class':'form-field stretch'}))
    text=forms.CharField(label='Text',required=False,widget=forms.Textarea(attrs={'placeholder':'Page Text here','class':'form-field description big','id':'textfield'}))
    question=forms.CharField(label='Text',required=False,widget=forms.Textarea(attrs={'placeholder':'Question here','class':'form-field description'}))
    choices=forms.CharField(label='Answer Choices',required=False,widget=forms.Textarea(attrs={'id':'json_input','style':'display:none;'}))
    correct_choices=forms.CharField(label='Correct Choices',required=False,widget=forms.Textarea(attrs={'id':'json_check','style':'display:none;'}))
    timer=forms.IntegerField(label='Timer',required=False,min_value=5,widget=forms.NumberInput(attrs={'class':'form-field'}))
    grade=forms.IntegerField(label='Correct Answer Grade',min_value=0,required=False,widget=forms.NumberInput(attrs={'class':'form-field'}))
    penalty=forms.IntegerField(label='Penalty',min_value=0,required=False,widget=forms.NumberInput(attrs={'class':'form-field'}))
'''
class AnswerTypeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
'''

class UserResponseText(forms.Form):
    user_response=forms.CharField(label='Type your answer below:',widget=forms.Textarea(attrs={'placeholder':'Type your answer here','class':'form-field description big'}))

class UserResponseSingular(forms.Form):
    #pass choices as an argument to response from the respective view
    user_response=forms.ChoiceField(label='Select your answer from the following options:',widget=forms.RadioSelect())

class UserResponseMultiple(forms.Form):
    user_response=forms.MultipleChoiceField(label='Select all correct answers below:',widget=forms.CheckboxSelectMultiple(),required=False)

class UserResponseFile(forms.Form):
    user_response=forms.FileField(required=False,label='Upload your file below:',widget=forms.FileInput(attrs={'class':'content center'}))

class UserGroupsForm(forms.Form):
    name=forms.CharField(label='Name',widget=forms.TextInput(attrs={'placeholder':'Group Name','class':'form-field'}))

class UserGet(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Student Username','class':'form-field'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
class CourseGet(forms.Form):
    course=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Course Name','class':'form-field'}))
    #deadline=forms.DateTimeField(widget=forms.DateTimeInput(),required=False)
    
class AssignmentDeadlines(forms.Form):
    deadline=forms.DateTimeField(required=False,widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}))

class UserDetailsForm(forms.Form):
    pfp=forms.ImageField(required=False,widget=forms.FileInput(attrs={'style':'margin-top: 0.5rem; margin-bottom: 0.5rem;'}))
    username=forms.CharField(required=False,widget=forms.TextInput(attrs={'placeholder':'Username','class':'form-field'}))
    old_password = forms.CharField(required=False,label='Old Password', widget=forms.PasswordInput(attrs={'placeholder': 'Old Password','class': 'form-field'}))
    password = forms.CharField(required=False,label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'New Password','class': 'form-field'}))
    password_verify = forms.CharField(required=False,label='Repeat Password', widget=forms.PasswordInput(attrs={'placeholder': 'Repeat New Password','class': 'form-field'}))
class NotificationForm(forms.Form):
    title=forms.CharField(label='Page Title',widget=forms.TextInput(attrs={'placeholder':'Notification Title','class':'form-field'}))
    text=forms.CharField(label='Text',required=False,widget=forms.Textarea(attrs={'placeholder':'Notification Text','class':'form-field stretch','style':'height:1.5rem;'}))

quizsite/backend/templates/backend/auth.html
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    {% if user_found %}
      <p class="text-2xl text-red-500">Sorry, that username already exists.</p>
    {% endif %}
    {% if password_mismatch %}
      <p class="text-2xl text-red-500">Sorry, passwords did not match.</p>
    {% endif %}
    {% if incomplete_form %}
      <p class="text-2xl text-red-500">Sorry, you should fill in all the credential fields.</p>
    {% endif %}
    <form class="content-center" action="/register/" method="post">
      {% csrf_token %}
      <div class="text-center">{{ form.as_p }}</div>
    </form>
  </body>
</html>

quizsite/backend/templates/backend/course_browse_end.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <!-- font import -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet" />
</head>
<!-- wanted to make it one template but thought that id rather not do that right now, maybe later -->
<style>
    input[type='checkbox'] {
        width: 1.5rem;
        height: 1.5rem;
    }

    input[type='radio'] {
        width: 1.5rem;
        height: 1.5rem;
    }
</style>

<body>
    <div class="split">
        <nav class="sidebar">
            <ul class="sidebar-list">
                <img class="icon" src="{% static 'hse_logo.svg' %}" alt="HSE Logo" />
                <li class="sidebar-element" onclick="window.location.href='/'">
                    <div class="sidebar-text">Home Page</div>

                </li>
                <li class="sidebar-element" onclick="window.location.href='/courses/'">
                    <div class="sidebar-text">Course Search</div>

                </li>
                {%if user|check_teacher%}
                <li class="sidebar-element" onclick="window.location.href='/groups/'">
                    <div class="sidebar-text">Student Groups</div>
                </li>
                {%endif%}
                {%if user|check_group_enrollment%}
                <li class="sidebar-element" onclick="window.location.href='/assignments/'">
                    <div class="sidebar-text">Handed-out Assignments</div>
                </li>
                {%endif%}
            </ul>
        </nav>
        <main>
            <span style="overflow: hidden;">
                <div class="main-div-quick-access">
                    <div style="display:block;">
                        <p onclick="window.location.href='/notifications/'" class="link-text">
                            {{user|get_notif_number}} notifications
                        </p>
                        <p onclick="window.location.href='/user/';" class="link-text">
                            Profile
                        </p>
                    </div>
                    <img class="pfp" src="{{user|get_pfp}}" />
                </div>
                <!--welcome-->
                <div style="overflow: hidden;">
                    <h2>
                        {{ course_name }}: End of the quiz
                    </h2>
                </div>
            </span>
            <br />
            <br />
            <hr />

            <span class="content center">
                <h1>Congratulations on quiz completion!</h1>
                <h2>Your score is: {{answer_sum}}/{{answer_max}}</h2>
                <button onclick="window.location.href='/courses/{{course_name}}'" class="course-button">Back to the quiz
                    page</button>
            </span>
        </main>
    </div>
</body>
<script>
    localStorage.clear();
</script>

</html>

quizsite/backend/templates/backend/course_browse_no_pages.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <!-- font import -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet" />
</head>
<!-- wanted to make it one template but thought that id rather not do that right now, maybe later -->
<style>
    input[type='checkbox'] {
        width: 1.5rem;
        height: 1.5rem;
    }

    input[type='radio'] {
        width: 1.5rem;
        height: 1.5rem;
    }
</style>

<body>
    <div class="split">
        <nav class="sidebar">
            <ul class="sidebar-list">
                <img class="icon" src="{% static 'hse_logo.svg' %}" alt="HSE Logo" />
                <li class="sidebar-element" onclick="window.location.href='/'">
                    <div class="sidebar-text">Home Page</div>

                </li>
                <li class="sidebar-element" onclick="window.location.href='/courses/'">
                    <div class="sidebar-text">Course Search</div>

                </li>
                {%if user|check_teacher%}
                <li class="sidebar-element" onclick="window.location.href='/groups/'">
                    <div class="sidebar-text">Student Groups</div>
                </li>
                {%endif%}
                {%if user|check_group_enrollment%}
                <li class="sidebar-element" onclick="window.location.href='/assignments/'">
                    <div class="sidebar-text">Handed-out Assignments</div>
                </li>
                {%endif%}
            </ul>
        </nav>
        <main>
            <span style="overflow: hidden;">
                <div class="main-div-quick-access">
                    <div style="display:block;">
                        <p onclick="window.location.href='/notifications/'" class="link-text">
                            {{user|get_notif_number}} notifications
                        </p>
                        <p onclick="window.location.href='/user/';" class="link-text">
                            Profile
                        </p>
                    </div>
                    <img class="pfp" src="{{user|get_pfp}}" />
                </div>
                <!--welcome-->
                <div style="overflow: hidden;">
                    <h2>
                        {{ course_name }}: No pages
                    </h2>
                </div>
            </span>
            <br />
            <br />
            <hr />

            <span class="content center">
                <h1>Looks like this course has no pages yet</h1>
                <h2>Please check in later.</h2>
                <button onclick="window.location.href='/courses/{{course_name}}'" class="course-button">Back to the
                    course
                    page</button>
            </span>
        </main>
    </div>
</body>

</html>

quizsite/backend/templates/backend/course_item.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  {% load filters %}
  <link rel="stylesheet" href="{% static 'style.css' %}" />
  <!-- font import -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
    rel="stylesheet" />
</head>
<!-- wanted to make it one template but thought that id rather not do that right now, maybe later -->

<body>
  <div class="split">
    <nav class="sidebar">
      <ul class="sidebar-list">
        <img class="icon" src="{% static 'hse_logo.svg' %}" alt="HSE Logo" />
        <li class="sidebar-element" onclick="window.location.href='/'">
          <div class="sidebar-text">Home Page</div>

        </li>
        <li class="sidebar-element" onclick="window.location.href='/courses/'">
          <div class="sidebar-text">Course Search</div>

        </li>
        {%if user|check_teacher%}
        <li class="sidebar-element" onclick="window.location.href='/groups/'">
          <div class="sidebar-text">Student Groups</div>
        </li>
        {%endif%}
        {%if user|check_group_enrollment%}
        <li class="sidebar-element" onclick="window.location.href='/assignments/'">
          <div class="sidebar-text">Handed-out Assignments</div>
        </li>
        {%endif%}
      </ul>
    </nav>
    <main>
      <div class="main-div-quick-access">
        <div style="display:block;">
          <p onclick="window.location.href='/notifications/'" class="link-text">
            {{user|get_notif_number}} notifications
          </p>
          <p onclick="window.location.href='/user/';" class="link-text">
            Profile
          </p>
        </div>
        <img class="pfp" src="{{user|get_pfp}}" />
      </div>
      <h2>Course Description</h2>
      <p onclick="window.location.href='/courses';" class="link-text">
        Back to course list </p>
      <span class="content center">
        <br />
        <br />
        <div class="user-face">
          <div class="assignments-box">
            <img class="course-image" src="{% static 'course.png' %}">
            <a class="course-text">{{ course_name }}</a>
          </div>
          <div class="user-link-spread">
            <p>Author: {{author_name}}</p>
            <p>Enrolled: 0</p>
            <p>Number of pages: {{n_pages}}</p>
          </div>
        </div>
      </span>
      <span class="content center row">
        {% if n_pages != 0 %}
        <button class="course-button"
          onclick="window.location.href='/courses/{{ course_name }}/browse/1';">Enroll</button>
        {%endif%}
        {% if owner %}
        <button class="course-button secondary"
          onclick="window.location.href='/courses/{{ course_name }}/edit/0';">Edit</button>
        {% endif %}
      </span>
      <hr>
      </hr>
      <h2>Course Description</h2>
      {{course_description}}
    </main>

  </div>
</body>

</html>

quizsite/backend/templates/backend/group_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <!-- font import -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet" />
</head>
<!-- wanted to make it one template but thought that id rather not do that right now, maybe later -->

<body>
    <div class="split">
        <nav class="sidebar">
            <ul class="sidebar-list">
                <img class="icon" src="{% static 'hse_logo.svg' %}" alt="HSE Logo" />
                <li class="sidebar-element" onclick="window.location.href='/'">
                    <div class="sidebar-text">Home Page</div>

                </li>
                <li class="sidebar-element" onclick="window.location.href='/courses/'">
                    <div class="sidebar-text">Course Search</div>

                </li>
                {%if user|check_teacher%}
                <li class="sidebar-element" onclick="window.location.href='/groups/'">
                    <div class="sidebar-text">Student Groups</div>
                </li>
                {%endif%}
                {%if user|check_group_enrollment%}
                <li class="sidebar-element" onclick="window.location.href='/assignments/'">
                    <div class="sidebar-text">Handed-out Assignments</div>
                </li>
                {%endif%}
            </ul>
        </nav>
        <main>
            <span style="overflow: hidden;">
                <div class="main-div-quick-access">
                    <div style="display:block;">
                        <p onclick="window.location.href='/notifications/'" class="link-text">
                            {{user|get_notif_number}} notifications
                        </p>
                        <p onclick="window.location.href='/user/';" class="link-text">
                            Profile
                        </p>
                    </div>
                    <img class="pfp" src="{{user|get_pfp}}" />
                </div>
                <!--welcome-->
                <div style="overflow: hidden;">
                    <h2>
                        {{ group_name }}: Group Deletion
                    </h2>
                </div>
            </span>
            <span class="content center">
                <h2>Are you sure you want to delete {{group_name}}?</h2>
            </span>
            <hr />
            <span class="content center">
                <div class="content center row">
                    <div>{{group_name}}</div>
                    <div>|</div>
                    <div>{{page_obj.title}}</div>
                    <div>|</div>
                    <div>{{page_obj.get_answer_type_display}}</div>
                </div>
            </span>
            <hr />
            <span class="content center">
                <p>Deletion of this group will cause you loosing access to all of your students' submitted answers, as
                    well as:</p>
                <ul>
                    <li>{{n_assignments}} assignment{%if n_assignments != 1 %}s{%endif%}</li>
                    <li>{{n_students}} added student{%if n_students != 1 %}s{%endif%}</li>
                    <li>All of the set deadlines information</li>
                </ul>
                <p>No users will be deleted.</p>

            </span>
            <span class="content center row">
                <button class="course-button" onclick="window.location.href='/groups/{{group_name}}/';">Abort</button>
                <button class="course-button secondary"
                    onclick="window.location.href='/groups/{{group_name}}/delete/?confirm=True';">Delete
                    The Group</button>
            </span>

        </main>
    </div>
</body>
<!--script src="{%static 'page_manager_trigger_warn.js' %}"></script-->

</html>